In [9]:
import pandas as pd
import ast

In [10]:
def expand(column):
    top_data = column['top']
    dict = {item['key'] : item['value'] for item in top_data}
    return pd.Series(dict)



def unstr_to_str_data(path, name):

    data = pd.read_excel(path)

    data.drop(['car_links','new_car_feature'], axis=1, inplace=True)

    # first columns name
    data['new_car_detail'] = data['new_car_detail'].apply(ast.literal_eval)
    new_car_detail_df = pd.json_normalize(data['new_car_detail'])

    # removing the column name and adding the new columns in old data
    data = pd.concat([data.drop(columns=['new_car_detail']), new_car_detail_df], axis=1) # First column over
    
    # second columns
    data['new_car_overview'] = data['new_car_overview'].apply(ast.literal_eval)
    new_car_overview_df = pd.json_normalize(data['new_car_overview'])

    new_columns = new_car_overview_df.apply(expand, axis=1)

    # removing the column top in df and adding the new_columns data
    new_car_overview_df = pd.concat([new_car_overview_df.drop(columns=['top']), new_columns], axis=1)

    # removing the column in old data and adding the df
    data = pd.concat([data.drop(columns=['new_car_overview']), new_car_overview_df], axis=1)

    # third columns

    data['new_car_specs'] = data['new_car_specs'].apply(ast.literal_eval)
    new_car_specs_df = pd.json_normalize(data['new_car_specs'])

    new_columns = new_car_specs_df.apply(expand, axis=1)

    new_car_specs_df = pd.concat([new_car_specs_df.drop(columns=['top']), new_columns], axis=1)

    flattened_data = []

    for car_spec in data['new_car_specs']:

        new_car_specs_data_df = {}

        for category in car_spec['data']:
            for item in category['list']:
                new_car_specs_data_df[item['key']] = item['value']

        flattened_data.append(new_car_specs_data_df)

    df = pd.DataFrame(flattened_data)

    new_car_specs_df = pd.concat([new_car_specs_df.drop(columns=['data']),df], axis=1)

    data = pd.concat([data.drop(columns=['new_car_specs']),new_car_specs_df], axis=1)

    data['City'] = name

    data.to_csv(f"cleaned_{name}_cars.csv")

    return data

In [11]:
path = r"C:\Users\GS0864\Downloads\bangalore_cars.xlsx"
name = "Banglore"

unstr_to_str_data(path, name)

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5,235-litres,NaN,NaN,Banglore
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,...,Ventilated Disc,Drum,NaN,NaN,"Tubeless,Radial",4,352-litres,16,NaN,Banglore
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,...,Disc,Drum,150 kmph,14.3 Seconds,Tubeless,5,242-litres,14,NaN,Banglore
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,...,Disc,Drum,172km/hr,14.2 Seconds,"Tubeless,Radial",4,407-litres,14,NaN,Banglore
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,...,Ventilated Disc,Solid Disc,190 Kmph,12 Seconds,"Tubeless,Radial",5,353-litres,16,NaN,Banglore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,0,Diesel,SUV,"1,56,039",Manual,2,2nd Owner,Toyota,Toyota Fortuner,2012,...,Ventilated Disc,Drum,176 Kmph,9.6 Seconds,"Tubeless,Radial",5,296-litres,17,NaN,Banglore
1477,0,Petrol,Sedan,"56,000",Manual,2,2nd Owner,Maruti,Maruti SX4,2008,...,Ventilated Disc,Drum,177 kmph,12.1 seconds,"Tubeless, Radial",4,505 litres,16,NaN,Banglore
1478,0,Petrol,Hatchback,"42,000",Manual,2,2nd Owner,Honda,Honda Brio,2014,...,Disc,Drum,164 Kmph,14.5 Seconds,"Tubeless,Radial",5,175-litres,NaN,NaN,Banglore
1479,0,Diesel,Hatchback,"93,003",Manual,1,1st Owner,Hyundai,Hyundai i20,2018,...,Disc,Drum,180 Kmph,11.9 Seconds,Tubeless,5,295-litres,16,NaN,Banglore
1480,0,Petrol,Hatchback,"36,000",Automatic,2,2nd Owner,Hyundai,Hyundai Grand i10,2017,...,Disc,Drum,165 Kmph,12.9 Seconds,Tubeless,5,256-liters,14,NaN,Banglore

In [12]:
path = r"C:\Users\GS0864\Downloads\chennai_cars.xlsx"
name = "Chennai"

unstr_to_str_data(path, name)

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Super Charger,Front Tread,Rear Tread,Gross Weight,Turning Radius,Top Speed,Acceleration,BoreX Stroke,Ground Clearance Unladen,City
0,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,Kia,Kia Sonet,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chennai
1,0,Petrol,Minivans,"20,687",Manual,1,1st Owner,Maruti,Maruti Eeco,2015,...,No,1280mm,1290mm,1540kg,4.5 metres,145 Kmph,15.7 Seconds,NaN,NaN,Chennai
2,0,Petrol,SUV,"30,000",Manual,1,1st Owner,Nissan,Nissan Magnite,2021,...,No,NaN,NaN,NaN,5.0,NaN,11.7,72.2 x 81.3,NaN,Chennai
3,0,Petrol,Hatchback,"59,247",Manual,1,1st Owner,Hyundai,Hyundai i10,2015,...,No,1400mm,1385mm,NaN,4.7 metres,165 Kmph,14.3 Seconds,NaN,NaN,Chennai
4,0,Petrol,Hatchback,"50,000",Manual,1,1st Owner,Honda,Honda Jazz,2015,...,No,NaN,NaN,NaN,5.1 meters,172 Kmph,13.7 Seconds,NaN,NaN,Chennai
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,0,Petrol,Hatchback,"42,891",Automatic,1,1st Owner,Maruti,Maruti Swift,2018,...,No,1530mm,1530mm,1315kg,4.8 Meters,NaN,NaN,NaN,NaN,Chennai
1415,0,Diesel,SUV,"59,100",Manual,1,1st Owner,Renault,Renault Duster,2018,...,No,1560mm,1567mm,1777kg,5.2 metres,156 Kmph,13.9 Seconds,NaN,NaN,Chennai
1416,0,Petrol,SUV,"55,913",Automatic,1,1st Owner,Tata,Tata Nexon,2018,...,No,1540 mm,1530 mm,NaN,5.1m,154.19 kmph,NaN,77x85.8,209 mm,Chennai
1417,0,Diesel,SUV,"65,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Tiguan,2017,...,No,1578mm,1568mm,2250kg,5.75meters,NaN,NaN,74.5 x 81 mm,NaN,Chennai
1418,0,Diesel,Sedan,"60,000",Automatic,1,1st Owner,BMW,BMW 3 Series GT,2019,...,No,1541 mm,1581 mm,NaN,5.5 metres,226 Kmph,7.7 Seconds,NaN,NaN,Chennai

In [13]:
path = r"C:\Users\GS0864\Downloads\delhi_cars.xlsx"
name = "Delhi"

unstr_to_str_data(path, name)

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Turning Radius,Top Speed,Acceleration,Gross Weight,Front Tread,Rear Tread,BoreX Stroke,Compression Ratio,Ground Clearance Unladen,City
0,0,Diesel,SUV,"10,000",Automatic,1,1st Owner,Kia,Kia Seltos,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Delhi
1,0,Petrol,SUV,"57,437",Manual,2,2nd Owner,Hyundai,Hyundai Creta,2016,...,5.3 metres,165 Kmph,10.5 Seconds,NaN,NaN,NaN,NaN,NaN,NaN,Delhi
2,0,Petrol,SUV,"8,000",Automatic,1,1st Owner,Mercedes-Benz,Mercedes-Benz GLC,2020,...,NaN,217 Kmph,NaN,2360kg,NaN,NaN,NaN,NaN,NaN,Delhi
3,0,Petrol,Hatchback,"28,151",Manual,2,2nd Owner,Maruti,Maruti Swift,2018,...,4.8,NaN,NaN,1335,1530,1530,NaN,NaN,NaN,Delhi
4,0,Petrol,SUV,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2017,...,5.3 metres,165 Kmph,10.5 Seconds,NaN,NaN,NaN,NaN,NaN,NaN,Delhi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,0,Petrol,Sedan,"60,000",Automatic,1,1st Owner,Honda,Honda City,2019,...,5.3 metres,195 Kmph,10 Seconds,1455kg,1490mm,1480mm,73.0 X 89.4 mm,10.3:1,NaN,Delhi
1481,0,Petrol,SUV,"20,000",Manual,1,1st Owner,Kia,Kia Sonet,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Delhi
1482,0,Petrol,Sedan,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Verna,2011,...,5.2 metres,196km/hr,10.5 Seconds,NaN,NaN,NaN,77.0mm X 85.44mm,10.5;1,NaN,Delhi
1483,0,Diesel,SUV,"38,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2019,...,5.3 metres,160.58kmph,10.83 s,NaN,NaN,NaN,NaN,NaN,190mm,Delhi
1484,0,Diesel,SUV,"7,000",Automatic,0,0th Owner,MG,MG Gloster,2023,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Delhi

In [14]:
path = r"C:\Users\GS0864\Downloads\hyderabad_cars.xlsx"
name = "Hyderabad"

unstr_to_str_data(path, name)

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Front Brake Type,Rear Brake Type,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Top Speed,Acceleration,Ground Clearance Unladen,City
0,0,Petrol,Hatchback,"20,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Polo,2022,...,Disc,Drum,"Tubeless,Radial",R16,5,280,NaN,NaN,NaN,Hyderabad
1,0,Petrol,Hatchback,"85,582",Manual,2,2nd Owner,Hyundai,Hyundai EON,2014,...,Disc,Drum,Tubeless,NaN,5,215-litres,135 Kmph,19 Seconds,NaN,Hyderabad
2,0,Petrol,SUV,"10,000",Manual,1,1st Owner,Hyundai,Hyundai Venue,2023,...,Disc,Drum,"Tubeless, Radial",NaN,5,NaN,NaN,NaN,NaN,Hyderabad
3,0,Petrol,Hatchback,"50,750",Manual,1,1st Owner,Maruti,Maruti Baleno,2017,...,Disc,Drum,"Tubeless,Radial",16,5,339-litres,180 Kmph,12.36 seconds,NaN,Hyderabad
4,0,Petrol,SUV,"10,000",Automatic,1,1st Owner,Mahindra,Mahindra Thar,2022,...,Disc,Drum,"Radial, Tubeless",18,3,NaN,NaN,NaN,NaN,Hyderabad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1478,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Mahindra,Mahindra XUV500,2013,...,Disc & Caliper Type,Disc & Caliper Type,"Tubeless,Radial",17,5,NaN,175 kmph,12.5 Seconds,NaN,Hyderabad
1479,0,Diesel,Sedan,"50,000",Automatic,1,1st Owner,Jaguar,Jaguar XF,2014,...,Disc,Disc,"Tubeless,Radial",20,4,540-litres,250 Kmph,6.4 Seconds,NaN,Hyderabad
1480,0,Diesel,Sedan,"1,20,000",Automatic,3,3rd Owner,BMW,BMW 5 Series,2018,...,Ventilated Disc,Ventilated Disc,"Tubeless, Runflat",R18,4,520-litres,235kmph,7.5,NaN,Hyderabad
1481,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Tata,Tata Nexon,2019,...,Disc,Drum,Tubeless Radial Tyres,NaN,5,350,154.19 kmph,13.25 Seconds,209 mm,Hyderabad
1482,0,Diesel,MUV,"1,00,000",Manual,1,1st Owner,Toyota,Toyota Innova,2015,...,Ventilated Disc,Drum,"Tubeless,Radial",15,5,300-litres,155 Kmph,13.3 Seconds,NaN,Hyderabad

In [15]:
path = r"C:\Users\GS0864\Downloads\jaipur_cars.xlsx"
name = "Jaipur"

unstr_to_str_data(path, name)

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Acceleration,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Gross Weight,BoreX Stroke,Compression Ratio,Ground Clearance Unladen,City
0,0,Diesel,Hatchback,"1,20,000",Manual,2,2nd Owner,Hyundai,Hyundai i20,2015,...,11.9 Seconds,Tubeless,16,5,295-litres,NaN,NaN,NaN,NaN,Jaipur
1,0,Petrol,Hatchback,"66,951",Manual,1,1st Owner,Maruti,Maruti Swift,2012,...,NaN,"Radial, Tubeless",NaN,5,268,1335,NaN,NaN,NaN,Jaipur
2,0,Petrol,Hatchback,"80,000",Automatic,2,2nd Owner,Maruti,Maruti Celerio,2016,...,15.05 Seconds,"Tubeless, Radial",NaN,5,235-litres,1250kg,73 X 82 mm,11.0:1,NaN,Jaipur
3,0,Petrol,Hatchback,"44,392",Manual,1,1st Owner,Hyundai,Hyundai Grand i10,2017,...,12.9 Seconds,Tubeless,NaN,5,256,NaN,NaN,NaN,NaN,Jaipur
4,0,Petrol,Hatchback,"40,000",Automatic,1,1st Owner,Maruti,Maruti Wagon R,2016,...,18.6 Seconds,Tubeless Tyres,NaN,5,180-liters,1350kg,69 x 72 mm,NaN,NaN,Jaipur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Chevrolet,Chevrolet Beat,2011,...,NaN,"Tubeless,Radial",14,5,170-litres,NaN,NaN,NaN,NaN,Jaipur
1116,0,Petrol,Hatchback,"70,000",Manual,1,1st Owner,Maruti,Maruti Alto,2007,...,17.7 seconds,"Tubeless,Radial",12,5,NaN,1140kg,68.5 x 72.0 mm,NaN,NaN,Jaipur
1117,0,Petrol,SUV,"20,000",Manual,1,1st Owner,Renault,Renault Kiger,2022,...,NaN,"Tubeless, Radial",16,5,405,NaN,NaN,NaN,NaN,Jaipur
1118,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Alto,2009,...,17.7 seconds,"Tubeless,Radial",12,5,NaN,1140kg,68.5 x 72.0 mm,NaN,NaN,Jaipur
1119,0,Petrol,Hatchback,"80,000",Manual,1,1st Owner,Maruti,Maruti Baleno,2018,...,12.36 seconds,"Tubeless,Radial",NaN,5,339-litres,1340kg,NaN,NaN,NaN,Jaipur

In [16]:
path = r"C:\Users\GS0864\Downloads\kolkata_cars.xlsx"
name = "Kolkata"

unstr_to_str_data(path, name)

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Rear Brake Type,Tyre Type,Alloy Wheel Size,No Door Numbers,Ground Clearance Unladen,Cargo Volumn,Compression Ratio,Acceleration,Top Speed,City
0,0,Petrol,Sedan,"70,000",Automatic,3,3rd Owner,Toyota,Toyota Camry,2014,...,Solid Disc,"Tubeless,Radial",17,4,NaN,NaN,NaN,NaN,NaN,Kolkata
1,0,Petrol,Hatchback,"23,981",Manual,1,1st Owner,Datsun,Datsun RediGO,2017,...,Drum,NaN,NaN,5,185mm,222,NaN,NaN,NaN,Kolkata
2,0,Petrol,SUV,"7,100",Automatic,1,1st Owner,Renault,Renault Kiger,2021,...,Drum,"Tubeless, Radial",NaN,5,NaN,405,NaN,NaN,NaN,Kolkata
3,0,Petrol,Hatchback,"71,574",Manual,2,2nd Owner,Hyundai,Hyundai i20,2011,...,Drum,"Tubeless,Radial",14,5,NaN,295 Lit,:1,12.96 Sec,NaN,Kolkata
4,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Audi,Audi Q3,2014,...,Drum,"Tubeless,Radial",16,5,NaN,460-litres,NaN,8.2 Seconds,212 Kmph,Kolkata
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,Maruti Celerio,2022,...,Drum,"Tubeless, Radial",NaN,5,NaN,313,NaN,NaN,NaN,Kolkata
1377,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Maruti,Maruti Alto 800,2014,...,Drum,Tubeless Tyres,NaN,5,NaN,177-litres,NaN,19 Seconds,140 kmph,Kolkata
1378,0,Petrol,Sedan,"50,000",Automatic,3,3rd Owner,Mercedes-Benz,Mercedes-Benz C-Class,2011,...,Solid Disc,"Tubeless,Radial",17,4,NaN,475-litres,9.3:1,8.8 Seconds,230km/hr,Kolkata
1379,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Ritz,2012,...,Drum,"Tubeless,Radial",14,5,NaN,236-liters,NaN,15 Seconds,156 Kmph,Kolkata
1380,0,Diesel,SUV,"1,20,000",Manual,2,2nd Owner,Renault,Renault Duster,2017,...,Drum,"Tubeless,Radial",16,5,NaN,410-litres,NaN,14.20 Seconds,168 Kmph,Kolkata